Repository Grupo43Moviles20251/Kotlin, pull requests merged in 2025-04, with the labels that each got.

#48 Feature/favorites screen
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/moviles2025/freshlink43/MainActivity.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/dto/ProductDto.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/dto/RestaurantDto.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/dto/RestaurantMapsDto.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/dto/UserDto.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/mappers/mappers.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/FavoriteRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/ForgotPasswordRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/HomeRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/LoginRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/RestaurantRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/SearchRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/SignUpRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/BackendServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/FirebaseServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/di/RepositoryModule.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/model/Product.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/model/Restaurant.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/forgotpass/ForgotPasswordViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/Product.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/MapFacade.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/MapViewComponent.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/Product.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/UbicationScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/UbicationViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/navigation/BottomNavManager.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/navigation/Header.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/navigation/NavGraph.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/navigation/NavRoutes.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/navigation/SplashScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/profile/ProfileScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/profile/ProfileViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/utils/Color.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/utils/Constants.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/utils/Theme.kt
  app/src/main/res/values/google_maps_api.xml
Labels: enhancement

#49 favorite screen terminada y tactica de local storage terminada.
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeViewModel.kt
Labels: enhancement

#52 escenario conectividad eventual + multithreading strategy
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/FavoriteRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginViewModel.kt
Labels: enhancement, question

#58 multithreading finished and BQ1
  app/build.gradle.kts
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/DetailRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/HomeRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/LoginRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/SearchRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/SignUpRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/BackendServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/FirebaseServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/detail/DetailViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpViewModel.kt
Labels: bug, enhancement

#60 Bugfix/bug with opening screens and login
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/BackendServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpViewModel.kt
Labels: bugfix

#61 Feature/cachingmanager
  app/build.gradle.kts
  app/src/main/kotlin/com/moviles2025/freshlink43/cacheHandler/Cache.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/HomeRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/di/NetworkModule.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/di/RepositoryModule.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/model/Restaurant.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/network/ConnectivityHandler.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/detail/DetailScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/detail/DetailViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/MapViewComponent.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/UbicationScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/UbicationViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/utils/NotConection.kt
  app/src/main/res/drawable/notconectionimage.png
Labels: enhancement

#64 bug de imagen en el profile
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/profile/ProfileScreen.kt
Labels: bugfix

#66 eventual conectivity search
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchViewModel.kt
Labels: enhancement

#68 Dev
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/moviles2025/freshlink43/cacheHandler/Cache.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/analytics/AnalyticsManager.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/DetailRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/HomeRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/repository/ProfileRepository.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/BackendServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/data/serviceadapters/FirebaseServiceAdapter.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/di/NetworkModule.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/di/RepositoryModule.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/model/Restaurant.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/network/ConnectivityHandler.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/detail/DetailScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/detail/DetailViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/favorites/FavoritesScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/login/LoginScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/MapViewComponent.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/UbicationScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/maps/UbicationViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/navigation/Header.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/profile/ProfileScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/profile/ProfileViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/search/SearchViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpScreen.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/ui/signup/SignUpViewModel.kt
  app/src/main/kotlin/com/moviles2025/freshlink43/utils/NotConection.kt
  app/src/main/res/drawable/ic_birthday.png
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/drawable/ic_mail.png
  app/src/main/res/drawable/notconectionimage.png
  gradle/libs.versions.toml
Labels: enhancement
